name: Large Tests
on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Test scenario tags"
jobs:
  large-tests:
    runs-on: kaiju
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-02-06
          override: true
          components: rustfmt, clippy
      - name: nanoGPT Mock
        run: cargo test --release --verbose tests::large_mock_::large_tests_1_expects -- --include-ignored
      - name: nanoGPT KZG prove and verify large tests
        run: cargo test --release --verbose tests::large_kzg_prove_and_verify_::large_tests_1_expects -- --include-ignored
      - name: Self Attention Mock
        run: cargo test --release --verbose tests::large_mock_::large_tests_0_expects -- --include-ignored
      - name: Self Attention KZG prove and verify large tests
        run: cargo test --release --verbose tests::large_kzg_prove_and_verify_::large_tests_0_expects -- --include-ignored
      - name: mobilenet Mock
        run: cargo test --release --verbose tests::large_mock_::large_tests_3_expects -- --include-ignored
      - name: mobilenet KZG prove and verify large tests
        run: cargo test --release --verbose tests::large_kzg_prove_and_verify_::large_tests_3_expects -- --include-ignored
